# Generated by Django 6.0.5 on 2026-05-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keiba_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorehistory',
            name='rows_data',
            field=models.JSONField(default=list),
        ),
    ]
