# Generated by Django 6.0.5 on 2026-05-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keiba_app', '0002_scorehistory_rows_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorehistory',
            name='exam_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='scorehistory',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
